---
- name: Ensure nginx is installed and running
  hosts: web_servers
  become: true

  tasks:
    - name: Install nginx
      ansible.builtin.package:
        name: nginx
        state: present

    - name: Enable and start nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true
---

- name: create database user
  hosts: db_servers
  become: true
  tasks:
    - name: create database user
      community.postgresql.postgresql_db:
        name: pharma_catalog
        owener: postgres
        state: present
        login_user: postgres
        login_password: mysecretpassword   

      

---
---
- name: Deploy MOTD and restart SSH if changed
  hosts: all
  become: true

  tasks:
    - name: Render /etc/motd from template
      ansible.builtin.template:
        src: motd.j2
        dest: /etc/motd
        owner: root
        group: root
        mode: '0644'
      notify: Restart SSH

  handlers:
    - name: Restart SSH
      ansible.builtin.service:
        name: "{{ 'sshd' if ansible_facts.os_family in ['RedHat','Rocky','Alma','Suse','Amazon'] else 'ssh' }}"
        state: restarted
