---
- name: Ensure stack and Traefik dirs exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  loop:
    - /opt/stacks
    - /var/lib/traefik
    - /var/lib/traefik/dynamic
    - /var/lib/traefik/certs

- name: Copy Wazuh stack file
  ansible.builtin.copy:
    src: "{{ playbook_dir | dirname }}/../../stack/wazuh-stack.yml"
    dest: /opt/stacks/wazuh-stack.yml
    owner: root
    group: root
    mode: "0644"

- name: Resolve effective secrets and host
  ansible.builtin.set_fact:
    indexer_password_effective: >-
      {{ vault_indexer_admin_password
         | default(lookup('env', 'INDEXER_PASSWORD'), true) }}
    wazuh_api_password_effective: >-
      {{ vault_wazuh_api_password
         | default(lookup('env', 'WAZUH_API_PASSWORD'), true) }}
    dashboard_password_effective: >-
      {{ vault_dashboard_admin_password
         | default(lookup('env', 'DASHBOARD_PASSWORD'), true) }}
    acme_email_effective: >-
      {{ vault_acme_email
         | default(lookup('env', 'ACME_EMAIL'), true) }}
    wazuh_host_effective: >-
      {{ wazuh_domain
         | default(lookup('env', 'WAZUH_HOST') | default('wazuh.local')) }}

- name: Deploy Wazuh stack (prune unused)
  community.docker.docker_stack:
    state: present
    name: wazuh
    compose:
      - /opt/stacks/wazuh-stack.yml
    prune: true
