---
- name: Create directory for stacks
  ansible.builtin.file:
    path: /opt/stacks
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Copy Wazuh stack file
  ansible.builtin.copy:
    src: "{{ playbook_dir | dirname }}/../..//stack/wazuh-stack.yml"
    dest: /opt/stacks/wazuh-stack.yml
    owner: root
    group: root
    mode: "0644"

- name: Create Traefik ACME directory
  ansible.builtin.file:
    path: /var/lib/traefik
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Create empty acme.json with strict perms
  ansible.builtin.copy:
    dest: /var/lib/traefik/acme.json
    content: ""
    owner: root
    group: root
    mode: "0400"

- name: Deploy Wazuh stack (prune unused services)
  community.docker.docker_stack:
    state: present
    name: wazuh
    compose:
      - /opt/stacks/wazuh-stack.yml
    prune: true
