---
site_name: Mini SOC
repo_url: https://github.com/<your-username>/<your-repo>
nav:
  - Home: index.md
  - Architecture: architecture.md
  - How to Run: usage.md
  - Detection Rules: rules.md
theme:
  name: material
plugins:
  - search
  - mermaid2
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true