site_name: Mini SOC
repo_url: https://github.com/BaderEddineBenhirt/mini-soc.git
nav:
  - Home: index.md
  - Architecture: architecture.md
  - Usage: usage.md
  - Detection Rules: rules.md
theme:
  name: material
plugins:
  - search
  - mermaid2
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
