---
- name: Deploy Wazuh on Swarm
  hosts: managers
  gather_facts: false
  collections:
    - community.docker
    - ansible.builtin

  vars:
    acme_email: "{{ lookup('env', 'ACME_EMAIL') | default(omit) }}"
    indexer_password: "{{ lookup('env', 'INDEXER_PASSWORD') | default(omit) }}"
    wazuh_api_password: "{{ lookup('env', 'WAZUH_API_PASSWORD') \
      | default(omit) }}"
    dashboard_username: "{{ lookup('env', 'DASHBOARD_USERNAME') \
      | default(omit) }}"
    dashboard_password: "{{ lookup('env', 'DASHBOARD_PASSWORD') \
      | default(omit) }}"
    wazuh_host: "{{ lookup('env', 'WAZUH_HOST') \
      | default(omit) }}"

  roles:
    - role: swarm_cluster
    - role: wazuh_stack
