---
- name: Remove Wazuh from Swarm
  hosts: managers
  gather_facts: false
  collections:
    - community.docker
    - ansible.builtin

  tasks:
    - name: Remove Wazuh stack
      community.docker.docker_stack:
        name: wazuh
        state: absent
        prune: true

    - name: Remove Wazuh overlay network
      community.docker.docker_network:
        name: wazuh
        state: absent

    - name: Remove Traefik overlay network
      community.docker.docker_network:
        name: traefik_proxy
        state: absent
