# .github/workflows/docs.yml
name: docs
on:
  push:
    branches: [main]
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'ansible/**'
      - '.github/workflows/**'
jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install MkDocs + plugins
        run: |
          pip install mkdocs-material mkdocs-mermaid2-plugin mkdocs-git-revision-date-localized-plugin
      - name: Generate role docs (example)
        run: |
          mkdir -p docs/refs
          ansible-galaxy collection install community.docker
          ansible-doc -t role wazuh_stack > docs/refs/role_wazuh_stack.md || true
      - name: Build site
        run: mkdocs build --strict
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
